#! /bin/sh

tmpfile=/tmp/txq$$

web_root="/~marty"
# file_root="/home/marty/website"
file_root="$WN_ROOT"

songdir=music/midi/songs

collect()
{
	nmatches=0
	while read x; do
		echo $x
		nmatches=`expr $nmatches + 1`
	done
}

plist()
{
	echo -n "<hr><h2>Individual selections:</h2><ul>"
	while read x; do
		f="$songdir/$x"
		echo "<li><a href=\"$web_root/$f\">$x</a>"
	done
	echo "</ul>"
}

echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "</head>"
echo "<body>"

if [ "$1" != "" ]; then
	echo -n "$1"
fi

collect > $tmpfile
echo -n "<h2>($nmatches matches found)</h2>"

echo "<hr><a href=\"$web_root/$SCRIPT_NAME?$2&rtype=zip\">Click Here for ZIPfile</a>"

plist < $tmpfile

echo "</body>"
echo "</html>"

rm -f $tmpfile
