#define		KEYUP		(-72)
#define		KEYDN		(-80)
#define		KEYLF		(-75)
#define		KEYRT		(-77)
#define		KEYHOME		(-71)
#define		KEYCHOME	(-119)
#define		KEYEND		(-79)
#define		KEYCEND		(-117)
#define		KEYPGUP 	(-73)
#define		KEYPGDN 	(-81)

