echo off
msc GETLINE /W2 ;
IF ERRORLEVEL 1 ECHO 
msc PFKEY /W2 ;
IF ERRORLEVEL 1 ECHO 
msc SCO /W2 ;
IF ERRORLEVEL 1 ECHO 
msc SCROLL /W2 ;
IF ERRORLEVEL 1 ECHO 
msc DATASEG /W2 ;
IF ERRORLEVEL 1 ECHO 
msc SPC /W2 ;
IF ERRORLEVEL 1 ECHO 
msc SCREEN /W2 ;
IF ERRORLEVEL 1 ECHO 
msc GETKEY /W2 ;
IF ERRORLEVEL 1 ECHO 
msc QUEUE /W2 ;
IF ERRORLEVEL 1 ECHO 
msc DOESC /W2 ;
IF ERRORLEVEL 1 ECHO 
msc DRAW /W2 ;
IF ERRORLEVEL 1 ECHO 
msc DOBS /W2 ;
IF ERRORLEVEL 1 ECHO 
msc PROCCMD /W2 ;
IF ERRORLEVEL 1 ECHO 
msc TG /W2 ;
IF ERRORLEVEL 1 ECHO 
