#define		_PFK(n)		(58+n)
#define		_PFHOME		(71)
#define		_PFUP  		(72)
#define		_PFPGUP		(73)
#define		_PFLEFT		(75)
#define		_PFRIGHT	(77)
#define		_PFEND 		(79)
#define		_PFDOWN		(80)
#define		_PFPGDN		(81)
#define		_PFINS 		(82)
#define		_PFDEL 		(83)
#define		_PFCTLLE 	(115)
#define		_PFCTLRI   	(116)
#define		_PFCTLEN 	(117)
#define		_PFCTLPD	(118)
#define		_PFCTLHO  	(119)
#define		_PFCTLPU	(132)
