/*

*/

//
//	ordering manager
//
class K_OrderingManager {
} ;

//
//	delivery manager
//
class K_DeliveryManager {
} ;

//
//	inventory manager
//
class K_InventoryManager {
} ;

//
//	catalog manager
//
class K_CatalogManager {
} ;

//
//	execution manager
//
class K_ExecutionManager {
} ;

//
//	category registry
//
class K_CategoryRegistry {
} ;


//
//	installation manager
//
class K_InstallationManager {
} ;



// end of file
