#! /usr/ucb/csh
#
# this is a c-shell script
#
# created in order to refresh my memory about c-shell scripts
#

switch ($#argv) 
case 0:
	echo "${0}: ${0} arg1 arg2 ..."
	exit 1
	breaksw
endsw

foreach i ($*)
	echo `basename $i '\..*'`
end

